-- Create Database System GoGame

CREATE DATABASE GoGame
GO
USE GoGame
GO

CREATE TABLE [MsCustomer] (
	CustomerID CHAR(5) PRIMARY KEY CHECK (CustomerID LIKE 'CU[0-9][0-9][0-9]'),
	CustomerName VARCHAR(50) NOT NULL,
	CustomerGender VARCHAR(10) CHECK (CustomerGender IN ('Male', 'Female')) NOT NULL,
	CustomerDOB DATE NOT NULL,
	CustomerPhoneNumber VARCHAR(15) NOT NULL
);

CREATE TABLE [MsStaff] (
	StaffID CHAR(5) PRIMARY KEY CHECK (StaffID LIKE 'ST[0-9][0-9][0-9]'),
	StaffName VARCHAR(50) NOT NULL,
	StaffGender VARCHAR(10) CHECK (StaffGender IN ('Male', 'Female')) NOT NULL,
	StaffDOB DATE NOT NULL,
	StaffSalary FLOAT NOT NULL,
	StaffPhoneNumber VARCHAR(15) NOT NULL,
	StaffAddress VARCHAR(50) NOT NULL
);

CREATE TABLE [MsSupplier] (
	SupplierID CHAR(5) PRIMARY KEY CHECK (SupplierID LIKE 'SU[0-9][0-9][0-9]'),
	SupplierName VARCHAR(50) NOT NULL,
	SupplierPhoneNumber VARCHAR(50) NOT NULL,
	SupplierAddress VARCHAR(50) NOT NULL,
);

CREATE TABLE [MsGameType] (
	GameTypeID CHAR(5) PRIMARY KEY CHECK (GameTypeID LIKE 'GT[0-9][0-9][0-9]'),
	GameTypeName VARCHAR(50) NOT NULL
);

CREATE TABLE [MsGame] (
	GameID CHAR(5) PRIMARY KEY CHECK (GameID LIKE 'GA[0-9][0-9][0-9]'),
	GameTypeID CHAR(5) FOREIGN KEY REFERENCES MsGameType(GameTypeID) ON UPDATE CASCADE ON DELETE CASCADE,
	GameName VARCHAR(50) NOT NULL,
	GamePrice FLOAT NOT NULL,
	ReleaseDate DATE CHECK (ReleaseDate < GETDATE()) NOT NULL
);

CREATE TABLE [SalesHeader] (
	SalesID CHAR(5) PRIMARY KEY CHECK (SalesID LIKE 'SA[0-9][0-9][0-9]'),
	StaffID CHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	CustomerID CHAR(5) FOREIGN KEY REFERENCES MsCustomer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE,
	SalesDate DATE CHECK (SalesDate < GETDATE()) NOT NULL
);

CREATE TABLE [SalesDetail] (
	SalesID CHAR(5) FOREIGN KEY REFERENCES SalesHeader(SalesID) ON UPDATE CASCADE ON DELETE CASCADE,
	GameID CHAR(5) FOREIGN KEY REFERENCES MsGame(GameID) ON UPDATE CASCADE ON DELETE CASCADE,
	SalesQuantity INT CHECK (SalesQuantity > 0) NOT NULL,
	PRIMARY KEY(SalesID, GameID)
);

CREATE TABLE [PurchaseHeader] (
	PurchaseID CHAR(5) PRIMARY KEY CHECK (PurchaseID LIKE 'PU[0-9][0-9][0-9]'),
	StaffID CHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	SupplierID CHAR(5) FOREIGN KEY REFERENCES MsSupplier(SupplierID) ON UPDATE CASCADE ON DELETE CASCADE,
	PurchaseDate DATE CHECK (PurchaseDate < GETDATE()) NOT NULL
);

CREATE TABLE [PurchaseDetail] (
	PurchaseID CHAR(5) FOREIGN KEY REFERENCES PurchaseHeader(PurchaseID) ON UPDATE CASCADE ON DELETE CASCADE,
	GameID CHAR(5) FOREIGN KEY REFERENCES MsGame(GameID) ON UPDATE CASCADE ON DELETE CASCADE,
	PurchaseQuantity INT CHECK (PurchaseQuantity > 0) NOT NULL,
	PRIMARY KEY(PurchaseID, GameID)
);
